# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.
from typing import List

# TODO: Improve this
def generate_fibonacci_sequence() -> List[int]:
    initial_list = [0, 1]
    while True:
        if initial_list[-1] + initial_list[-2] > 4000000:
            break
        else:
            initial_list.append(initial_list[-1] + initial_list[-2])
    return initial_list


fibonnaci_list = generate_fibonacci_sequence()
sum_even_values = sum(filter(lambda x: x % 2 == 0, fibonnaci_list))
print(sum_even_values)
